# Generated by Django 5.1.3 on 2026-07-22 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150, verbose_name="Guest's name")),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('SUITE', 'Deluxe Suite')], max_length=20, verbose_name='Room type')),
                ('check_in', models.DateField(verbose_name='Check-in date')),
                ('check_out', models.DateField(verbose_name='Departure date')),
                ('guests_count', models.PositiveIntegerField(default=1, verbose_name='Number of guests')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special requests')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request creation date')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
